[routeros_message_type_lookup]
filename = routeros_message_type.csv

[routeros_auth_lookup]
filename = routeros_auth.csv

[routeros_fw_lookup]
filename = routeros_fw.csv

[routeros_telegraf_host]
SOURCE_KEY = _raw
REGEX = url\":\"http:\/\/([^\/]+)\/[^"]+
DEST_KEY = MetaData:Host
FORMAT = host::$1

[routeros_telegraf_source]
SOURCE_KEY = _raw
REGEX = url\":\"http:\/\/[^\/]+(\/[^"]+)
DEST_KEY = MetaData:Source
FORMAT = source::$1

[routeros_telegraf_name]
SOURCE_KEY = _raw
REGEX = \},\"name\":\"([^\"]+)
FORMAT = configname::$1
WRITE_META = true
LOOKAHEAD = 18192

[routeros_telegraf_raw]
INGEST_EVAL = _raw=json_extract($pd:_raw$,"fields")

[routeros_telegraf_indexfields]
REGEX = ([^"]+)"\s*:\s*("(?:[^"\\]|\\.)*"|[^\s,]*)(?:\s*,|\s*})
FORMAT = $1::$2
REPEAT_MATCH = true
WRITE_META = true
LOOKAHEAD = 18192

[routeros_set_sourcetype_cef]
REGEX = .+\sCEF:.+
DEST_KEY = MetaData:Sourcetype
FORMAT = sourcetype::routeros:cef
WRITE_META = true